wandb_version: 1

lr:
  desc: null
  value:
    value: 0.001
epochs:
  desc: null
  value:
    value: 4
batch_size:
  desc: null
  value:
    value: 16
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.2
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705513498.724915
    t:
      1:
      - 5
      - 53
      - 55
      - 105
      2:
      - 5
      - 53
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.11.7
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
