workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: gcr.io/mlops-411012/trainer
      args:
        - python
        - -u
        - src/train_model.py