workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      imageUri: gcr.io/mlops-411012/predictor:version-amd64
      args:
        - python
        - -u
        - src/predict_model.py
        - /data/processed/X_test.csv


