global:
  scrape_interval: 1s  # Scrape timer

scrape_configs:
  - job_name: 'predictor'
    static_configs:
      - targets: ['localhost:8000']  # The main application container's /metrics endpoint.
