name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r portfolio/requirements.txt
        pip install git+https://github.com/skfolio/skfolio.git --no-cache-dir
        pip install portfolio/. --no-deps --no-cache-dir
   
    - name: Install DVC
      run: pip install dvc

    - name: Check DVC version
      run: dvc version
    
    - name: Install DVC GCS dependency
      run: pip install 'dvc-gs'

    - name: Get data
      run: |
       cd portfolio
       dvc pull

    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v

